export const DEEP = [
  ["love", 8, "What's your favorite way to be loved?"],
  ["love", 7, "What makes you feel cared for in a way that's easy to miss?"],
  ["love", 8, "When you feel loved, what do you start doing differently?"],
  ["love", 7, "Do you fall in love with potential or with what's already there?", "Potential", "What's there"],
  ["love", 8, "What does feeling chosen look like to you?"],
  ["love", 7, "What's a small loving gesture that means more than a big production?"],
  ["love", 9, "What are you like when you feel securely loved?"],
  ["love", 7, "Words, presence, or follow-through — which feels most like love?", "Words / presence", "Follow-through"],
  ["love", 8, "What do you hope people never have to earn from you?"],
  ["love", 7, "How do you show love when you're tired?"],
  ["love", 8, "What's something about love you believe now that you didn't at 18?"],
  ["love", 7, "Is love, for you, more of a feeling or a practice?", "Feeling", "Practice"],
  ["love", 8, "What makes affection feel safe instead of performative?"],
  ["love", 9, "What kind of love are you trying to become capable of giving?"],
  ["love", 7, "What do you want love to make room for in your life?"],
  ["love", 8, "When do you feel most loving toward the world, not just a person?"],
  ["love", 7, "What's a myth about romance you're glad you unlearned?"],
  ["love", 8, "How do you want to be loved on an ordinary Wednesday?"],

  ["connection", 8, "What makes you feel truly understood?"],
  ["connection", 7, "What does a real conversation require from you?"],
  ["connection", 8, "When do you feel most accompanied, even in silence?"],
  ["connection", 7, "Do you connect through talking, doing, or sitting together?", "Talking", "Doing / sitting"],
  ["connection", 9, "What do you wish people knew about how you attach to others?"],
  ["connection", 7, "What makes you feel lonely even in a room of people?"],
  ["connection", 8, "What kind of check-in actually lands for you?"],
  ["connection", 7, "Deep and rare, or frequent and light — what's your connection diet?", "Deep and rare", "Frequent and light"],
  ["connection", 8, "What's something someone can do that makes you feel less alone in five minutes?"],
  ["connection", 9, "Where do you still hope to be known more fully?"],
  ["connection", 7, "What topic makes you feel closest to someone?"],
  ["connection", 8, "How do you know a connection is mutual, not just hoped-for?"],
  ["connection", 7, "Do you need a lot of togetherness, or a lot of thoughtful distance?", "Togetherness", "Thoughtful distance"],
  ["connection", 8, "What does being 'gotten' feel like in your body?"],
  ["connection", 9, "What's a kind of closeness you're still learning how to receive?"],
  ["connection", 7, "When someone remembers a small detail about you, what does that do?"],
  ["connection", 8, "What makes community feel real instead of social?"],
  ["connection", 7, "Who do you become around people who really see you?"],

  ["identity", 8, "When do you feel most like yourself?"],
  ["identity", 7, "What part of you is easy for people to see, and what part takes time?"],
  ["identity", 8, "What name, role, or story about you feels most true?"],
  ["identity", 7, "Are you more of a roots person or a becoming person?", "Roots", "Becoming"],
  ["identity", 9, "What is something you're afraid people will misunderstand about you?"],
  ["identity", 8, "Which parts of you are inherited, and which did you choose?"],
  ["identity", 7, "What community, culture, or place still lives in how you move through the world?"],
  ["identity", 8, "When have you felt like you had to translate yourself?"],
  ["identity", 7, "Do you feel more like yourself in familiar rooms or in new ones?", "Familiar", "New"],
  ["identity", 9, "What do you want to be known for besides what you do?"],
  ["identity", 8, "What's a contradiction in you that actually makes sense?"],
  ["identity", 7, "Which season of you are you most loyal to?"],
  ["identity", 8, "What did you have to grow into before you could say it out loud?"],
  ["identity", 9, "Where are you still negotiating who you are with who you were expected to be?"],
  ["identity", 7, "Home in a city, home in people, or home in a feeling?", "People", "A feeling / place"],
  ["identity", 8, "What makes you feel like you don't have to perform?"],
  ["identity", 7, "What's a thread that's been true about you since you were young?"],
  ["identity", 8, "If you introduced yourself without your job or roles, what would you say?"],

  ["selfImage", 7, "What do you like about how you show up in the world?"],
  ["selfImage", 8, "What story about yourself are you trying to retire?"],
  ["selfImage", 7, "Do you see yourself more clearly in stillness or in action?", "Stillness", "Action"],
  ["selfImage", 8, "What kind of attention feels nourishing versus exposing?"],
  ["selfImage", 9, "Where are you learning to be on your own side?"],
  ["selfImage", 7, "What compliment do you hope is true?"],
  ["selfImage", 8, "How has your relationship with your reflection changed over time?"],
  ["selfImage", 7, "Are you harder on yourself in private or in comparison?", "Private", "Comparison"],
  ["selfImage", 8, "What would being gentler with yourself look like this week?"],
  ["selfImage", 9, "What part of you deserves more credit than you give it?"],
  ["selfImage", 7, "When do you feel at home in your own skin?"],
  ["selfImage", 8, "What outside measure of worth are you trying not to worship?"],
  ["selfImage", 7, "Do you believe people when they say kind things about you?", "Often", "It's hard"],
  ["selfImage", 8, "What does dignity mean to you on a regular day?"],
  ["selfImage", 9, "What are you practicing seeing in yourself that used to be invisible?"],
  ["selfImage", 7, "Who in your life reflects you back in a way you trust?"],
  ["selfImage", 8, "What would you keep about yourself even if nobody praised it?"],
  ["selfImage", 7, "How do you talk to yourself when you make a small mistake?"],

  ["vulnerability", 8, "What helps you tell the truth about how you feel?"],
  ["vulnerability", 7, "Do you open up in a rush or in careful layers?", "In a rush", "In layers"],
  ["vulnerability", 9, "What does being emotionally safe with someone look like?"],
  ["vulnerability", 8, "What's hard for you to ask for even when you need it?"],
  ["vulnerability", 7, "Humor, competence, or helpfulness — which can become your armor?", "Humor / competence", "Helpfulness"],
  ["vulnerability", 8, "When you share something tender, what do you hope happens next?"],
  ["vulnerability", 9, "What's a kind of honesty you're practicing?"],
  ["vulnerability", 7, "Do you feel braver writing it or saying it?", "Writing", "Saying it"],
  ["vulnerability", 8, "What makes you shut down, and what helps you come back?"],
  ["vulnerability", 9, "Where do you still want to be met without having to explain everything?"],
  ["vulnerability", 7, "What's a small risk of honesty that paid off?"],
  ["vulnerability", 8, "How can someone make it easier for you to be real?"],
  ["vulnerability", 7, "Is vulnerability, for you, a gift or a last resort?", "A gift", "A last resort"],
  ["vulnerability", 8, "What do you need to hear after you've been brave?"],
  ["vulnerability", 9, "What are you tired of carrying alone that isn't a crisis — just heavy?"],
  ["vulnerability", 7, "Who taught you, accidentally or on purpose, that sharing could be safe?"],
  ["vulnerability", 8, "What's the difference between oversharing and being known, for you?"],
  ["vulnerability", 8, "What would it mean to be seen and still stay?"],

  ["fear", 8, "What is something you're afraid of losing that isn't a possession?"],
  ["fear", 7, "Do your fears show up as control, avoidance, or overthinking?", "Control / avoidance", "Overthinking"],
  ["fear", 8, "What fear gets quieter when you're with the right person?"],
  ["fear", 9, "What are you afraid people will think if they see the unedited you?"],
  ["fear", 7, "Courage for you: doing it scared, or waiting until you're ready?", "Doing it scared", "Waiting until ready"],
  ["fear", 8, "What future version of life are you a little afraid to want?"],
  ["fear", 7, "What everyday fear is actually about belonging?"],
  ["fear", 9, "How do you want to be supported when you're afraid — not fixed, supported?"],
  ["fear", 8, "What fear have you already walked through that changed you?"],
  ["fear", 7, "Does naming a fear make it smaller or bigger for you?", "Smaller", "Bigger"],
  ["fear", 8, "What would you try if embarrassment wasn't on the table?"],
  ["fear", 9, "What kind of safety lets your nervous system believe you're okay?"],
  ["fear", 7, "Are you more afraid of being too much or not enough?", "Too much", "Not enough"],
  ["fear", 8, "What fear is really a longing in disguise?"],
  ["fear", 7, "When you're scared, do you want company or competence from others?", "Company", "Competence"],
  ["fear", 8, "What does bravery look like in your actual life, not in movies?"],
  ["fear", 9, "What are you learning to trust despite the fear?"],
  ["fear", 7, "What fear did someone help you put down?"],

  ["growth", 8, "What kind of person do you want to become?"],
  ["growth", 7, "What are you in the middle of becoming, even if it's unfinished?"],
  ["growth", 8, "What old survival strategy are you trying to outgrow?"],
  ["growth", 9, "What do you wish you could tell your younger self — without rewriting their path?"],
  ["growth", 7, "Growth for you: more softness, more backbone, or both?", "Softness", "Backbone"],
  ["growth", 8, "What are you practicing that nobody can see yet?"],
  ["growth", 9, "What hurt taught you something you still wouldn't choose again — and that's okay?"],
  ["growth", 7, "Do you grow more from love or from limits?", "Love", "Limits"],
  ["growth", 8, "What does healing look like on a Tuesday, not a milestone day?"],
  ["growth", 9, "Where are you asking more of yourself in a way that feels fair?"],
  ["growth", 7, "What are you unlearning that used to feel like personality?"],
  ["growth", 8, "Who are you becoming in relationships, specifically?"],
  ["growth", 7, "Is your growth louder in how you rest or how you work?", "Rest", "Work"],
  ["growth", 8, "What would 'integrated' feel like for you?"],
  ["growth", 9, "What part of your story are you trying to hold with more compassion?"],
  ["growth", 7, "What teacher, book, or season changed your inner weather?"],
  ["growth", 8, "What are you no longer available for?"],
  ["growth", 8, "How will you know you're growing in the direction you mean to?"],

  ["regret", 7, "What's a small regret that taught you a preference?"],
  ["regret", 8, "What do you wish you'd said sooner in a relationship that still matters?"],
  ["regret", 7, "Do you regret things you did, or things you didn't do, more often?", "Things I did", "Things I didn't"],
  ["regret", 8, "What would you do differently with a year of your life, knowing what you know?"],
  ["regret", 9, "How do you forgive yourself without pretending it didn't happen?"],
  ["regret", 7, "Is there a door you didn't walk through that still waves sometimes?"],
  ["regret", 8, "What kindness do you wish you'd offered — including to yourself?"],
  ["regret", 7, "Would you rather redo a conversation or a decision?", "Conversation", "Decision"],
  ["regret", 8, "What did regret teach you about your values?"],
  ["regret", 9, "What are you trying not to turn into a life sentence?"],
  ["regret", 7, "How do you want people to talk with you about the past?"],
  ["regret", 8, "What's a 'I knew better and still' moment you're gentler about now?"],
  ["regret", 7, "Do you make peace by understanding or by making amends?", "Understanding", "Amends"],
  ["regret", 8, "What would repairing something still possible look like?"],
  ["regret", 9, "What do you hope you won't regret about this season of your life?"],
  ["regret", 7, "What's a chance you didn't take that you're oddly grateful about now?"],
  ["regret", 8, "How do you want to treat future-you when present-you is unsure?"],
  ["regret", 8, "What does a clean goodbye mean to you?"],

  ["meaning", 8, "What does happiness mean to you, in practice?"],
  ["meaning", 7, "What makes a day feel like it counted?"],
  ["meaning", 8, "Where do you find meaning that isn't productivity?"],
  ["meaning", 9, "What do you want your life to have been about, besides achievement?"],
  ["meaning", 7, "Beauty, usefulness, or love — which orients you most?", "Beauty / love", "Usefulness"],
  ["meaning", 8, "What ordinary scene feels sacred to you?"],
  ["meaning", 7, "Do you look for meaning or make it?", "Look for it", "Make it"],
  ["meaning", 8, "What question do you keep living inside of?"],
  ["meaning", 9, "When have you felt part of something larger than your own story?"],
  ["meaning", 7, "What do you want more of: wonder, peace, or purpose?", "Wonder / peace", "Purpose"],
  ["meaning", 8, "What loss of meaning would actually scare you?"],
  ["meaning", 7, "Nature, art, people, or ideas — where does awe live?", "Nature / art", "People / ideas"],
  ["meaning", 8, "What makes suffering feel less pointless, if anything does?"],
  ["meaning", 9, "How do you want to be remembered by the people who really knew you?"],
  ["meaning", 7, "Is a good life, to you, more peaceful or more alive?", "Peaceful", "Alive"],
  ["meaning", 8, "What are you loyal to even when it's inconvenient?"],
  ["meaning", 8, "What does 'enough' mean in a life?"],
  ["meaning", 7, "Where do you feel most awake?"],

  ["purpose", 8, "What kind of work or offering feels like it uses the real you?"],
  ["purpose", 7, "Do you think of purpose as a calling or as a series of seasons?", "A calling", "Seasons"],
  ["purpose", 8, "Who are you hoping to be useful to?"],
  ["purpose", 9, "What would you still do if nobody clapped?"],
  ["purpose", 7, "Purpose in public or purpose in private care?", "Public", "Private care"],
  ["purpose", 8, "What problem in the world quietly bothers you in a personal way?"],
  ["purpose", 7, "Are you building, healing, teaching, or making?", "Building / making", "Healing / teaching"],
  ["purpose", 8, "What does a purposeful week contain?"],
  ["purpose", 9, "Where might you be confusing other people's purpose with yours?"],
  ["purpose", 7, "If purpose had a texture, would it be ambitious or quiet?", "Ambitious", "Quiet"],
  ["purpose", 8, "What gift of yours wants a better home?"],
  ["purpose", 9, "What are you willing to be mediocre at so you can be devoted to something else?"],
  ["purpose", 7, "Service, craft, or relationship as your main offering?", "Service / craft", "Relationship"],
  ["purpose", 8, "How do you want your days to feel if the big dream takes years?"],
  ["purpose", 8, "What would it mean to live on purpose without being self-important?"],
  ["purpose", 7, "Who benefits when you're at your most honest?"],
  ["purpose", 8, "What are you here to practice, even if you never master it?"],
  ["purpose", 9, "What legacy is small enough to start this year?"],

  ["future", 7, "What do you hope is true about your life in five years?"],
  ["future", 8, "What kind of older person do you want to be?"],
  ["future", 7, "Adventure or rootedness in the next chapter?", "Adventure", "Rootedness"],
  ["future", 8, "What are you planting now that you won't harvest soon?"],
  ["future", 9, "What future are you a little scared you might actually get?"],
  ["future", 7, "Do you plan the future or listen for it?", "Plan", "Listen"],
  ["future", 8, "What do you want more time for before life gets louder again?"],
  ["future", 7, "City, somewhere quieter, or you don't know yet?", "City", "Quieter"],
  ["future", 8, "Who do you want beside you in the ordinary future, not just the highlight reel?"],
  ["future", 9, "What would you like to be proud of when you look back at this age?"],
  ["future", 7, "Hope for you: a feeling or a discipline?", "Feeling", "Discipline"],
  ["future", 8, "What are you unwilling to postpone indefinitely?"],
  ["future", 7, "More freedom or more belonging ahead?", "Freedom", "Belonging"],
  ["future", 8, "How do you want to spend a random Thursday at 70?"],
  ["future", 9, "What future conversation do you hope you'll be brave enough to have?"],
  ["future", 7, "Would you rather know the plot or keep the surprise?", "Know the plot", "Keep the surprise"],
  ["future", 8, "What does a life with enough softness in it look like from here?"],
  ["future", 8, "What are you building that isn't a career?"],

  ["values", 8, "What value do you hope people can feel in how you treat them?"],
  ["values", 7, "Honesty or harmony, when they collide in a small way?", "Honesty", "Harmony"],
  ["values", 8, "What belief about people have you earned the hard way?"],
  ["values", 9, "What are you not willing to become, even if it would be easier?"],
  ["values", 7, "Loyalty, curiosity, or justice — which sits at your table first?", "Loyalty / curiosity", "Justice"],
  ["values", 8, "Where do your values show up when nobody is grading you?"],
  ["values", 7, "Do you believe people can change in the ways that matter?", "Yes", "I'm careful"],
  ["values", 8, "What does a good person mean to you, without cliché?"],
  ["values", 9, "What value did you inherit, and which one did you choose?"],
  ["values", 7, "Faith, doubt, or a private mix — how do you live with big questions?", "Faith / devotion", "Doubt / mix"],
  ["values", 8, "What line will you not cross to be liked?"],
  ["values", 8, "How do you want to use whatever power you have?"],
  ["values", 7, "Is kindness the floor or the ceiling for you?", "The floor", "The ceiling"],
  ["values", 9, "What would it cost you to live more aligned — and is it worth it?"],
  ["values", 8, "What do you owe strangers, in your own ethics?"],
  ["values", 7, "Rules or wisdom — what do you trust more in gray areas?", "Rules", "Wisdom"],
  ["values", 8, "What belief keeps you company when things are uncertain?"],
  ["values", 8, "What does integrity look like when you're tired and nobody would know?"],

  ["relationships", 8, "What makes a relationship feel strong to you?"],
  ["relationships", 7, "Repair or romance — which do you think keeps a bond alive?", "Repair", "Romance"],
  ["relationships", 9, "What are you still learning about being close to someone?"],
  ["relationships", 8, "How do you want to fight — if you have to — with someone you love?"],
  ["relationships", 7, "Independence together or we-ness, as a default?", "Independence", "We-ness"],
  ["relationships", 8, "What does devotion look like without self-erasure?"],
  ["relationships", 9, "Where do you need more courage in how you love people?"],
  ["relationships", 7, "Daily togetherness or spaciousness with deep reunions?", "Daily togetherness", "Spaciousness"],
  ["relationships", 8, "What promise do you try to keep in every important relationship?"],
  ["relationships", 9, "What kind of partner, friend, or family member are you trying to be when it's hard?"],
  ["relationships", 8, "What does trust rebuild from, for you?"],
  ["relationships", 7, "Neediness versus care — where do you draw a kind line?"],
  ["relationships", 8, "How do you want someone to love you when you are not impressive?"],
  ["relationships", 9, "What are you done pretending doesn't matter in closeness?"],
  ["relationships", 7, "Shared values or shared delight — which is the load-bearing wall?", "Values", "Delight"],
  ["relationships", 8, "What does a home with another person feel like, if it's going well?"],
  ["relationships", 8, "When you imagine lasting love, what is actually happening on a random weekend?"],
  ["relationships", 7, "What do you hope people feel after they've been in a relationship with you?"],

  ["needs", 8, "What do you need most when you are not okay?"],
  ["needs", 7, "Reassurance, space, or practical help — which is your first language?", "Reassurance / space", "Practical help"],
  ["needs", 9, "What need do you still feel awkward naming?"],
  ["needs", 8, "How can someone love you in a way your nervous system believes?"],
  ["needs", 7, "Do you need to be asked, or do you need people to notice?", "Asked", "Noticed"],
  ["needs", 8, "What does rest require for you besides sleep?"],
  ["needs", 9, "Where have you been over-functioning instead of asking?"],
  ["needs", 7, "Touch, words, or time — which fills you fastest when you're depleted?", "Touch / words", "Time"],
  ["needs", 8, "What need, when met, makes all the other ones quieter?"],
  ["needs", 9, "What are you learning you cannot outsource?"],
  ["needs", 7, "Is it easier for you to give care or receive it?", "Give", "Receive"],
  ["needs", 8, "What kind of consistency helps you feel secure?"],
  ["needs", 7, "When your needs conflict with someone else's, what do you hope happens?"],
  ["needs", 8, "What does being emotionally fed look like in a week?"],
  ["needs", 9, "What need did you used to call 'too much'?"],
  ["needs", 7, "Solitude as a need or connection as a need — which runs out first?", "Solitude", "Connection"],
];
