/** Together — questions answered about the other person, or about the two of you. */
export const TOGETHER = [
  ["everyday", 2, "If you went to the store, what snack or drink would I be, and why?"],
  ["comfort", 3, "What's something I do that makes you feel the most comfortable and safe?"],
  ["hope", 3, "What is one thing about me you hope never changes?"],
  ["everyday", 1, "What do I order that you secretly think of as my drink?"],
  ["everyday", 1, "What's my tell when I'm pretending I'm not tired?"],
  ["everyday", 1, "If my laugh were a sound in the house, what would it be?"],
  ["everyday", 2, "What's the first thing you notice when I walk into a room?"],
  ["everyday", 1, "What weather am I, on a regular Tuesday?"],
  ["everyday", 2, "What's a small habit of mine you could pick me out of a crowd by?"],
  ["everyday", 1, "If I were a time of day, which one, and why?"],
  ["everyday", 2, "What's something I always do with my hands when I'm thinking?"],
  ["everyday", 1, "What song starts playing in your head when I text you first?"],
  ["everyday", 2, "What's my version of coming home?"],
  ["everyday", 1, "If I were a seat in a café, which one would I claim?"],
  ["everyday", 2, "What's a tiny thing I do in the morning that you've started to wait for?"],
  ["everyday", 1, "What color do I leave in a room after I leave it?"],
  ["everyday", 2, "What's the face I make when I'm trying not to smile?"],
  ["everyday", 1, "If I were a grocery-store aisle, which one?"],
  ["everyday", 2, "What's something I always check twice, even when I don't need to?"],
  ["everyday", 1, "What do I sound like when I'm concentrating?"],
  ["everyday", 2, "What's my unofficial uniform when nobody's watching?"],
  ["everyday", 1, "If I were a kind of rain, what kind?"],
  ["everyday", 2, "What's a phrase I say that already belongs to both of us?"],
  ["everyday", 1, "What do I do with leftovers that tells you who I am?"],
  ["everyday", 2, "What's my tell when a room is too loud for me?"],
  ["everyday", 1, "If I were a kitchen tool, which one, and why?"],
  ["everyday", 2, "What's something I always notice that other people miss?"],
  ["everyday", 1, "What time of night am I most myself?"],
  ["everyday", 2, "What's the first thing I reach for when I sit down?"],
  ["everyday", 1, "If my energy had a temperature, what's the usual setting?"],
  ["everyday", 2, "What's a chore I make look strangely tender?"],
  ["everyday", 1, "What do I do when I don't know where to put my hands?"],
  ["everyday", 2, "What's my version of knocking on wood?"],
  ["everyday", 1, "If I were a mug in the cupboard, which one would I be?"],
  ["comfort", 2, "When I'm quiet, how do you know whether to come closer or let me be?"],
  ["comfort", 3, "What's a way I take care of you that I might not even count as care?"],
  ["comfort", 2, "Where in a room do you feel safest sitting with me?"],
  ["comfort", 3, "What's something I do with my voice that settles you?"],
  ["comfort", 2, "When you're spiraling, what's the first thing I do that actually helps?"],
  ["comfort", 3, "What's a boundary of yours I respect in a way that makes you trust me more?"],
  ["comfort", 2, "What's my version of a weighted blanket?"],
  ["comfort", 3, "When have I made a hard day feel smaller just by being in it?"],
  ["comfort", 2, "What's something I never rush you through?"],
  ["comfort", 3, "What's a way I hold space that you wish more people knew how to do?"],
  ["comfort", 2, "What's the safest version of silence we have?"],
  ["comfort", 3, "What's something I do after a fight that tells you we're still us?"],
  ["comfort", 2, "Where do I put my hand that you don't have to ask for?"],
  ["comfort", 3, "What's a fear of yours I treat as real, not dramatic?"],
  ["comfort", 2, "What's my tell that I'm listening with my whole body, not just waiting?"],
  ["comfort", 3, "What's something I protect for you without making a speech about it?"],
  ["comfort", 2, "When you're overstimulated, what do I do that actually lands?"],
  ["comfort", 3, "What's a way I've shown you that your softness is not a problem here?"],
  ["comfort", 2, "What's the kindest correction you've ever felt from me?"],
  ["comfort", 3, "What's something I remember about your body that isn't about looking?"],
  ["comfort", 2, "When you can't find words, how do I usually meet you?"],
  ["comfort", 3, "What's a way I make our home feel like yours, not just mine?"],
  ["comfort", 2, "What's my version of sitting on the floor with you?"],
  ["comfort", 3, "What's something I do that lets you be messy without performing okayness?"],
  ["comfort", 2, "What's the check-in from me that never feels like a quiz?"],
  ["comfort", 3, "When have I stayed when leaving would have been easier to look at?"],
  ["comfort", 2, "What's a small ritual we have that is actually a safety net?"],
  ["comfort", 3, "What's something I never use against you later?"],
  ["comfort", 2, "How do you know, in my face, that you're not too much?"],
  ["comfort", 3, "What's a way I repair that you trust more than an apology alone?"],
  ["comfort", 2, "What's the temperature of the room when I'm being gentle on purpose?"],
  ["hope", 3, "What quality of mine do you hope I never sand down to be easier?"],
  ["hope", 3, "What's a way I love that you hope I keep even if the world rewards a colder version?"],
  ["hope", 2, "What's something about how I move through a day that you never want me to optimize away?"],
  ["hope", 3, "What's a stubbornness in me you hope I keep?"],
  ["hope", 2, "What's a softness you hope I never apologize for?"],
  ["hope", 3, "What's one way I laugh that you hope never gets quieter?"],
  ["hope", 2, "What's a curiosity of mine you hope doesn't get practical and die?"],
  ["hope", 3, "What's a loyalty in me you hope I never call naïve?"],
  ["hope", 2, "What's something I still get excited about that you hope I never outgrow?"],
  ["hope", 3, "What's a way I tell the truth that you hope I don't learn to sand down?"],
  ["hope", 2, "What's a ritual of mine that looks small and you hope I keep forever?"],
  ["hope", 3, "What's a kindness I do when nobody's scoring that you hope I never stop?"],
  ["hope", 2, "What's something about my taste you hope never becomes 'more mature'?"],
  ["hope", 3, "What's a way I take people seriously that you hope I never call embarrassing?"],
  ["hope", 2, "What's a weird little hope I have that you want me to keep saying out loud?"],
  ["hope", 3, "What's a way I rest that you hope I never treat as lazy?"],
  ["hope", 2, "What's something I still believe that you hope the years don't talk me out of?"],
  ["hope", 3, "What's a way I show up for other people that you hope I keep showing up for myself, too?"],
  ["hope", 2, "What's a messiness in me you hope I never fully tidy?"],
  ["hope", 3, "What's one thing about how I love you that you hope stays this specific?"],
  ["hope", 2, "What's a song, joke, or bit of me you hope never gets retired?"],
  ["hope", 3, "What's a way I get earnest that you hope I never learn to be cooler than?"],
  ["hope", 2, "What's something I do with mornings you hope I keep?"],
  ["hope", 3, "What's a way I forgive that you hope I never confuse with forgetting myself?"],
  ["hope", 2, "What's a childhood leftover in me you hope I never fully put away?"],
  ["hope", 3, "What's one thing about my attention you hope never gets divided into nothing?"],
  ["hope", 2, "What's a way I get nerdy that you hope I never hide?"],
  ["noticing", 2, "What's something I think I hide well that you see anyway?"],
  ["noticing", 2, "What's a tiny change in me you notice before I mention it?"],
  ["noticing", 1, "What's my tell when I like someone in a room and I'm trying to be cool?"],
  ["noticing", 2, "What's a way I light up that I don't think anyone clocks?"],
  ["noticing", 2, "What's something I always underestimate about myself that you don't?"],
  ["noticing", 1, "What's the first thing that goes quiet in me when I'm sad?"],
  ["noticing", 2, "What's a pride I have that I pretend is casual?"],
  ["noticing", 2, "What's my tell when I'm about to be brave?"],
  ["noticing", 1, "What's something I always notice on other people first?"],
  ["noticing", 2, "What's a way I get shy that looks like something else?"],
  ["noticing", 2, "What's the version of me that shows up when I'm around my people?"],
  ["noticing", 1, "What's my tell that a compliment actually landed?"],
  ["noticing", 2, "What's something I protect with a joke?"],
  ["noticing", 2, "What's a skill of mine you use more than I admit I have?"],
  ["noticing", 1, "What's the face I make when I'm translating my feelings into something polite?"],
  ["noticing", 2, "What's a way I take up space that you love watching?"],
  ["noticing", 2, "What's something I'm tender about that I file under 'practical'?"],
  ["noticing", 1, "What's my tell when I'm impressed and trying not to show it?"],
  ["noticing", 2, "What's a contradiction in me that you find oddly consistent?"],
  ["noticing", 2, "What's something I always remember that surprises even me?"],
  ["noticing", 1, "What's the way I enter a conversation I'm not sure I belong in?"],
  ["noticing", 2, "What's a kindness I do that I would never put on a résumé?"],
  ["noticing", 2, "What's my tell when I'm homesick for a version of myself?"],
  ["noticing", 1, "What's something I collect without calling it collecting?"],
  ["noticing", 2, "What's a way I get competitive that you find endearing?"],
  ["noticing", 2, "What's something I always do for strangers that tells you my ethics?"],
  ["noticing", 1, "What's the posture I take when I'm listening to something I might disagree with?"],
  ["noticing", 2, "What's a dream of mine I mention like it's a joke?"],
  ["noticing", 2, "What's my tell when I'm proud of you and trying to play it cool?"],
  ["noticing", 1, "What's something I always underestimate until I'm in the middle of it?"],
  ["noticing", 2, "What's a way I get quiet that means I'm actually full, not empty?"],
  ["noticing", 2, "What's something I notice about rooms that other people walk past?"],
  ["play", 1, "If I were a board game, which one, and would you still play me?"],
  ["play", 2, "What's a bit we do that you hope we never explain to anyone?"],
  ["play", 1, "If we had a theme song nobody else was allowed to use, what would it be?"],
  ["play", 2, "What's the funniest thing I do when I think I'm being smooth?"],
  ["play", 1, "If I were a dessert, too sweet or the good kind of too much?"],
  ["play", 2, "What's a dare you'd only give me, never a stranger?"],
  ["play", 1, "If we opened a tiny shop, what would we sell badly and love anyway?"],
  ["play", 2, "What's my funniest 'I'm an expert' voice, and what subject is it always about?"],
  ["play", 1, "If I were a carnival ride, which one, and would you get on twice?"],
  ["play", 2, "What's a nickname you've almost given me and then swallowed?"],
  ["play", 1, "If we were a weather system, what would the forecast say?"],
  ["play", 2, "What's the silliest way I try to win an argument?"],
  ["play", 1, "If I were a plant, indoor or feral, and how often do I need water?"],
  ["play", 2, "What's a conspiracy we have about a stranger we've only seen once?"],
  ["play", 1, "If my laugh were a sitcom character, who?"],
  ["play", 2, "What's something I do that always makes you snort even when the room is serious?"],
  ["play", 1, "If we had a secret handshake, what would the last move be?"],
  ["play", 2, "What's my most committed bit when I'm trying to make you laugh on a bad day?"],
  ["play", 1, "If I were a midnight snack, leftovers or something we have to make?"],
  ["play", 2, "What's a game I take too seriously, and do you let me?"],
  ["play", 1, "If we were a two-person band, who plays what, and what's our one hit?"],
  ["play", 2, "What's the dumbest hill I'll die on that you find charming?"],
  ["play", 1, "If I were a texting style, punctuation or chaos?"],
  ["play", 2, "What's a voice I do that you can never unhear?"],
  ["play", 1, "If we got matching tattoos that were a little ugly on purpose, what would they be?"],
  ["play", 2, "What's my tell when I'm about to be unhinged in a fun way?"],
  ["play", 1, "If I were a holiday, which one, and would the decorations be extra?"],
  ["play", 2, "What's a bit of gossip we'd never spread, but we'd definitely discuss?"],
  ["play", 1, "If we had a flag, what would be on it that we'd never explain?"],
  ["play", 2, "What's the funniest way I say I love you without saying I love you?"],
  ["play", 1, "If I were a pair of shoes, practical or a problem, and why?"],
  ["play", 2, "What's a movie we'd recast ourselves in, badly?"],
  ["care", 3, "What's a way I show love that doesn't look like the movies?"],
  ["care", 2, "What's something I always remember to ask about later?"],
  ["care", 3, "When I'm taking care of you, what do you wish I'd let you do for me?"],
  ["care", 2, "What's a practical thing I do that you feel in your chest?"],
  ["care", 3, "What's a way I check on you that never feels like surveillance?"],
  ["care", 2, "What's something I always pack for you, emotionally?"],
  ["care", 3, "What's a need of yours I met before you had language for it?"],
  ["care", 2, "What's my version of bringing soup?"],
  ["care", 3, "What's a way I advocate for you when you're not in the room?"],
  ["care", 2, "What's something I always do after you've had a hard conversation with someone else?"],
  ["care", 3, "What's a way I love you that I learned, not that I arrived knowing?"],
  ["care", 2, "What's the errand I run that is actually devotion?"],
  ["care", 3, "What's something I never make you earn?"],
  ["care", 2, "What's my tell that I'm about to take something off your plate?"],
  ["care", 3, "What's a way I stay when your mood isn't convenient?"],
  ["care", 2, "What's something I always notice you're carrying before you set it down?"],
  ["care", 3, "What's a way I make your body feel like a place, not a project?"],
  ["care", 2, "What's the text I send that is actually a hand on your back?"],
  ["care", 3, "What's something I protect in you that you used to think you had to hide?"],
  ["care", 2, "What's my version of waiting up?"],
  ["care", 3, "What's a way I love you that costs me a little pride, and you notice?"],
  ["care", 2, "What's something I always do with your name in other people's mouths?"],
  ["care", 3, "What's a way I show up for the unglamorous version of your life?"],
  ["care", 2, "What's the chore I do that means 'I see the week you're having'?"],
  ["care", 3, "What's something I never make a production of, that is still a gift?"],
  ["care", 2, "What's my tell when I'm choosing you in a small, boring way?"],
  ["care", 3, "What's a way I hold your stories — do I keep them, return them, or both?"],
  ["care", 2, "What's something I always do at the end of your hard day without being asked?"],
  ["care", 3, "What's a way I make asking 'are you okay' feel like a door, not a test?"],
  ["care", 2, "What's the way I say goodnight that is actually a promise?"],
  ["care", 3, "What's something I do with your family, or the lack of it, that you feel in your ribs?"],
  ["care", 2, "What's my version of saving you the last bite?"],
  ["us", 2, "What's a sentence that already belongs to both of us?"],
  ["us", 3, "When did we start feeling like a we, and what was the small proof?"],
  ["us", 2, "What's a place that is ours even if other people go there too?"],
  ["us", 3, "What's a story about us you tell yourself when you're scared?"],
  ["us", 2, "What's something we do badly together that you still love?"],
  ["us", 3, "What's a way we're similar that still surprises you?"],
  ["us", 2, "What's a way we're different that actually makes the days work?"],
  ["us", 3, "What's an inside joke that would sound like nothing and means the whole house?"],
  ["us", 2, "What's a photo of us that isn't on a phone, just in your head?"],
  ["us", 3, "What's a hard thing we got through that you wouldn't want to have done with anyone else?"],
  ["us", 2, "What's our unofficial holiday?"],
  ["us", 3, "What's a way I change when you're in the room, for the better?"],
  ["us", 2, "What's something we always argue about that is actually about care?"],
  ["us", 3, "What's a quiet agreement we have that we've never written down?"],
  ["us", 2, "What's the version of us that shows up at 1 a.m.?"],
  ["us", 3, "What's a way we've disappointed each other and still chosen to stay curious?"],
  ["us", 2, "What's a meal that tastes like us?"],
  ["us", 3, "What's something you know about my past that you hold gently?"],
  ["us", 2, "What's a walk we take that isn't really about walking?"],
  ["us", 3, "What's a way I've become more myself because of you?"],
  ["us", 2, "What's our tell, as a pair, when a room isn't for us?"],
  ["us", 3, "What's a fear we share that we don't usually say in company?"],
  ["us", 2, "What's a song that is a timestamp for us?"],
  ["us", 3, "What's something I do that makes you feel chosen, not just included?"],
  ["us", 2, "What's a tradition we accidentally started?"],
  ["us", 3, "What's a way we repair that is uniquely ours?"],
  ["us", 2, "What's the object in this house that is actually a memory?"],
  ["us", 3, "What's a compliment about us you'd only say to me, not to a group?"],
  ["us", 2, "What's a silence we have that other people might misread?"],
  ["us", 3, "What's something about how we fight that you actually trust?"],
  ["us", 2, "What's a nickname the world doesn't get?"],
  ["us", 3, "What's a way we take turns being the brave one?"],
  ["future", 3, "What's something you hope we still do when we're older and slower?"],
  ["future", 2, "What's a version of a home you can already half-see with me in it?"],
  ["future", 3, "What's a hard season you hope we get to have together, not avoid?"],
  ["future", 2, "What's a trip that isn't about the destination so much as who we'd be on it?"],
  ["future", 3, "What's one thing you hope I still ask you in ten years?"],
  ["future", 2, "What's a skill you hope we learn side by side?"],
  ["future", 3, "What's a way you hope we stay beginners with each other?"],
  ["future", 2, "What's a table you hope we keep setting, even if the chairs change?"],
  ["future", 3, "What's something you hope we never get efficient at?"],
  ["future", 2, "What's a future ordinary morning you can already hear?"],
  ["future", 3, "What's a fear about time you hope we tell the truth about, together?"],
  ["future", 2, "What's a tradition you hope we invent before anyone else names it for us?"],
  ["future", 3, "What's one way you hope I still look at you when the newness is gone?"],
  ["future", 2, "What's a problem you hope we get good at solving as a team?"],
  ["future", 3, "What's something you hope we still get shy about?"],
  ["future", 2, "What's a room you hope we have someday, and what would we do in it at 11 p.m.?"],
  ["future", 3, "What's a way you hope we talk about money, bodies, or family without flinching?"],
  ["future", 2, "What's a small anniversary you hope we keep, not just the obvious one?"],
  ["future", 3, "What's something you hope we still argue about because it means we still care?"],
  ["future", 2, "What's a version of rest you hope we get better at taking together?"],
  ["future", 3, "What's one story you hope we get to tell about how we stayed?"],
  ["future", 2, "What's a kindness you hope we keep doing for strangers, as a pair?"],
  ["future", 3, "What's something you hope never becomes 'just how we are' if it starts to hurt?"],
  ["future", 2, "What's a future quiet you can already sit in with me?"],
  ["future", 3, "What's a way you hope we keep choosing each other when it's boring?"],
  ["future", 2, "What's a garden, literal or not, you hope we tend?"],
  ["future", 3, "What's one thing you hope I never stop telling you, even when you already know?"],
  ["future", 2, "What's a door you hope we leave unlocked for each other?"],
  ["future", 3, "What's a future version of us you'd like to leave a note for?"],
  ["future", 2, "What's something you hope we still get lost looking for, on purpose?"],
];
