export const PERSONAL = [
  ["personality", 4, "What's something people often get right about you on the first meeting?"],
  ["personality", 5, "What's something people often misunderstand about you?"],
  ["personality", 4, "Are you more of a planner or an improviser?", "Planner", "Improviser"],
  ["personality", 5, "What trait of yours is both a gift and a headache?"],
  ["personality", 4, "Do you process out loud or quietly first?", "Out loud", "Quietly first"],
  ["personality", 6, "When do you feel most like the 'real' version of yourself around others?"],
  ["personality", 4, "What's a compliment you never know how to receive?"],
  ["personality", 5, "What does confidence look like on you, not on other people?"],
  ["personality", 4, "Introvert battery or extrovert battery, in practice?", "Needs solitude", "Needs people"],
  ["personality", 5, "What's a small decision that actually says a lot about you?"],
  ["personality", 6, "What are you like when you feel safe?"],
  ["personality", 4, "Are you more loyal to routines or to moods?", "Routines", "Moods"],
  ["personality", 5, "What's a label you've been given that never quite fit?"],
  ["personality", 4, "Do you remember facts or feelings from a conversation more?", "Facts", "Feelings"],
  ["personality", 5, "What's something you're stubborn about in a way you respect?"],
  ["personality", 6, "How do you know when you actually trust someone?"],
  ["personality", 4, "Are you funnier in a group or one-on-one?", "Group", "One-on-one"],
  ["personality", 5, "What's a part of your personality you grew into rather than were born with?"],
  ["personality", 4, "Do you like being asked a lot of questions, or does it feel like a spotlight?", "I like it", "Spotlight"],

  ["friendship", 4, "What makes you feel like someone is actually your friend?"],
  ["friendship", 5, "What's your favorite way to spend time with a close friend?"],
  ["friendship", 4, "Do you prefer a wide circle or a tiny inner circle?", "Wide circle", "Tiny circle"],
  ["friendship", 6, "What's something a friend did that you still think about, in a good way?"],
  ["friendship", 5, "How do you usually show people you care?"],
  ["friendship", 4, "Are you the planner of the hangout or the grateful plus-one?", "Planner", "Plus-one"],
  ["friendship", 5, "What do you need from friends when you're having a rough week?"],
  ["friendship", 6, "What's hard for you about staying close to people over time?"],
  ["friendship", 4, "Voice notes, long texts, or 'want to call?'", "Voice notes / texts", "Calls"],
  ["friendship", 5, "What's a friendship rule you didn't know you had until someone broke it?"],
  ["friendship", 4, "Inside jokes or deep talks — which bonds you faster?", "Inside jokes", "Deep talks"],
  ["friendship", 6, "Who has influenced the kind of friend you try to be?"],
  ["friendship", 5, "How do you handle it when a friend needs space?"],
  ["friendship", 4, "Are you easy to make plans with, or do you need a runway?", "Easy", "Need a runway"],
  ["friendship", 5, "What's something you wish friends asked you more often?"],
  ["friendship", 6, "When have you felt most chosen as a friend?"],
  ["friendship", 4, "Group hang or one-on-one catch-up?", "Group", "One-on-one"],
  ["friendship", 5, "What's your apology style with friends?"],
  ["friendship", 4, "Do you remember birthdays, or are you the 'I'm sorry I'm late' person?", "I remember", "I'm late-ish"],

  ["relationships", 5, "What makes you feel appreciated by someone close to you?"],
  ["relationships", 6, "What helps you feel comfortable around someone new?"],
  ["relationships", 4, "Quality time, words, or helpful actions — which lands first?", "Time / words", "Helpful actions"],
  ["relationships", 5, "What's a green flag you notice faster than you used to?"],
  ["relationships", 6, "How do you like to be checked on?"],
  ["relationships", 5, "What's something that helps you feel close after you've been busy?"],
  ["relationships", 4, "Do you fall into closeness quickly or slowly?", "Quickly", "Slowly"],
  ["relationships", 6, "What does a secure relationship feel like in ordinary Tuesday terms?"],
  ["relationships", 5, "What's a boundary you communicate better now?"],
  ["relationships", 4, "Big talk at night or over breakfast?", "Night", "Breakfast"],
  ["relationships", 6, "What makes you feel respected when you disagree?"],
  ["relationships", 5, "How do you like to celebrate small wins with someone?"],
  ["relationships", 4, "Public affection or private affection, if you had to pick a default?", "Public", "Private"],
  ["relationships", 6, "What's something you hope people never have to guess about you?"],
  ["relationships", 5, "What does 'being on your team' look like?"],
  ["relationships", 4, "Do you like surprise plans or shared planning?", "Surprises", "Shared planning"],
  ["relationships", 6, "When you miss someone, what do you actually miss?"],
  ["relationships", 5, "What's a tiny ritual that makes a relationship feel like a relationship?"],
  ["relationships", 4, "Repair after conflict: talk it out soon or take a beat first?", "Soon", "Take a beat"],

  ["goals", 4, "What's something you're currently trying to get better at?"],
  ["goals", 5, "What's a goal you want that isn't impressive on paper but matters to you?"],
  ["goals", 4, "Do you like big five-year plans or next-three-months plans?", "Five years", "Three months"],
  ["goals", 6, "What's something you've always wanted to learn?"],
  ["goals", 5, "What would 'a good year' look like for you, honestly?"],
  ["goals", 4, "Are you more motivated by a deadline or by a vibe?", "Deadline", "Vibe"],
  ["goals", 5, "What's a skill you wish you had more time for?"],
  ["goals", 6, "What kind of life are you quietly building toward?"],
  ["goals", 4, "Public accountability or private notebooks?", "Public", "Private"],
  ["goals", 5, "What's a goal you released, and how did that feel?"],
  ["goals", 4, "Would you rather master one thing or try ten?", "Master one", "Try ten"],
  ["goals", 6, "What does progress feel like in your body, not just on a list?"],
  ["goals", 5, "Who do you become a little more like when you're chasing something?"],
  ["goals", 4, "Morning ambition or late-night ambition?", "Morning", "Late night"],
  ["goals", 5, "What's a small goal you could finish this month that would feel real?"],
  ["goals", 6, "What are you unwilling to sacrifice for a goal?"],
  ["goals", 4, "Do you like vision boards, spreadsheets, or neither?", "Visual / lists", "Neither"],
  ["goals", 5, "What's a dream you don't talk about much yet?"],
  ["goals", 4, "Finish what you start, or follow the spark?", "Finish", "Follow the spark"],

  ["accomplishments", 4, "What's something you're really proud of?"],
  ["accomplishments", 5, "What's a quiet win nobody clapped for that still counts?"],
  ["accomplishments", 4, "Do you celebrate wins or immediately look at the next thing?", "Celebrate", "Next thing"],
  ["accomplishments", 6, "What's something you finished that you weren't sure you could?"],
  ["accomplishments", 5, "What's a compliment you actually believed?"],
  ["accomplishments", 4, "Would you rather be known for talent or for follow-through?", "Talent", "Follow-through"],
  ["accomplishments", 5, "What's a hard thing you did that looks easy in hindsight?"],
  ["accomplishments", 6, "Who helped you become someone who could do that?"],
  ["accomplishments", 4, "Trophies and titles, or private proof?", "Titles", "Private proof"],
  ["accomplishments", 5, "What's something you taught yourself that still surprises you?"],
  ["accomplishments", 6, "When did you last feel proud in a way that wasn't about other people?"],
  ["accomplishments", 4, "Do you keep old certificates, tickets, or notes?", "Yes", "Not really"],
  ["accomplishments", 5, "What's a 'small' skill you're quietly excellent at?"],
  ["accomplishments", 6, "What's an accomplishment that cost more than people know?"],
  ["accomplishments", 4, "Team win or solo win — which tastes better?", "Team", "Solo"],
  ["accomplishments", 5, "What's something you want to be proud of a year from now?"],
  ["accomplishments", 4, "Do you like being celebrated in the moment or later, privately?", "In the moment", "Later / private"],
  ["accomplishments", 5, "What's a challenge you signed up for on purpose?"],
  ["accomplishments", 6, "How do you want people to describe what you're good at?"],

  ["memories", 5, "What's a memory that still feels warm when you revisit it?"],
  ["memories", 4, "Smell, song, or place — what time-travels you fastest?", "Smell / song", "Place"],
  ["memories", 6, "What's a moment you didn't know was important until later?"],
  ["memories", 5, "What's a childhood object, room, or meal you can still describe?"],
  ["memories", 4, "Do you keep a lot of photos, or just a few that matter?", "Lots of photos", "A few"],
  ["memories", 6, "What's a memory you like telling because it shows who you were becoming?"],
  ["memories", 5, "What's the kindest ordinary day you remember?"],
  ["memories", 4, "Are you the family historian or the 'wait, when was that?' person?", "Historian", "Wait, when?"],
  ["memories", 6, "What's a place that holds more than one version of you?"],
  ["memories", 5, "What's a laugh you can still hear if you think about it?"],
  ["memories", 4, "Souvenirs or stories — how do you keep trips?", "Souvenirs", "Stories"],
  ["memories", 6, "What's something you wish you had asked someone while you still could?"],
  ["memories", 5, "What's a school-year memory that still feels vivid?"],
  ["memories", 4, "Do you remember conversations word-for-word or in impressions?", "Word-for-word", "Impressions"],
  ["memories", 5, "What's a holiday or season that always comes with a specific memory?"],
  ["memories", 6, "What's a memory that taught you what you value?"],
  ["memories", 4, "Would you rather have a perfect video of a day, or keep it fuzzy and yours?", "Perfect video", "Keep it fuzzy"],
  ["memories", 5, "What's something you hope you never forget?"],
  ["memories", 5, "What's a first — first job, first trip, first apartment — that still lives in you?"],

  ["growth", 5, "What's something you've learned from a mistake?"],
  ["growth", 6, "What's a belief you outgrew?"],
  ["growth", 4, "Do you change in leaps or in slow layers?", "Leaps", "Slow layers"],
  ["growth", 5, "What's a piece of advice you actually used?"],
  ["growth", 6, "What's something you're kinder about now than you used to be?"],
  ["growth", 4, "Therapy talk, journaling, walking it out — what helps you grow?", "Talking / writing", "Walking it out"],
  ["growth", 5, "What's a fear that got smaller because you did the thing anyway?"],
  ["growth", 6, "Who has influenced you the most, and in what way?"],
  ["growth", 4, "Do you like being told the hard truth or the gentle version first?", "Hard truth", "Gentle first"],
  ["growth", 5, "What's a habit you built that quietly upgraded your life?"],
  ["growth", 6, "What's something you wish you were better at — and why that thing?"],
  ["growth", 4, "Books, people, or lived experience as your main teacher?", "Books / people", "Lived experience"],
  ["growth", 5, "What's a version of you that you're grateful you aren't anymore?"],
  ["growth", 6, "How do you know you're actually growing, not just busy?"],
  ["growth", 4, "Public resolutions or private experiments?", "Public", "Private"],
  ["growth", 5, "What's a compliment that became a standard you now try to live up to?"],
  ["growth", 6, "What did a difficult season teach you that a easy season couldn't?"],
  ["growth", 4, "Do you like before-and-after stories or in-progress stories?", "Before / after", "In progress"],
  ["growth", 5, "What's one thing you'd tell last-year's you without lecturing them?"],

  ["family", 5, "What's a family tradition you actually like?"],
  ["family", 4, "Are you more like one side of your family, or a mix nobody predicted?", "One side", "A mix"],
  ["family", 6, "What's something you learned at home that you still use?"],
  ["family", 5, "How does your family show care, in their language?"],
  ["family", 4, "Big family gatherings: energizing or exhausting?", "Energizing", "Exhausting"],
  ["family", 6, "What's a story your family tells about you that you have mixed feelings about?"],
  ["family", 5, "What kind of family member do you try to be?"],
  ["family", 4, "Chosen family, given family, or both in different ways?", "Chosen", "Given"],
  ["family", 6, "What's something you hope to keep from how you were raised?"],
  ["family", 5, "What's something you hope to do differently?"],
  ["family", 4, "Phone calls, group chats, or seeing each other in person?", "Calls / chats", "In person"],
  ["family", 6, "When have you felt most at home with the people who know your history?"],
  ["family", 5, "What's a small family object, recipe, or phrase that carries a lot?"],
  ["family", 4, "Do you like looking at old photos together?", "Yes", "Not really"],
  ["family", 5, "What's a family skill — cooking, fixing, hosting — that got passed down?"],
  ["family", 6, "What does support from family look like when it's actually helpful?"],
  ["family", 4, "Holidays: the whole production or keep it simple?", "The production", "Keep it simple"],
  ["family", 5, "Who in your wider circle feels like family even if they aren't?"],
  ["family", 5, "What's a family value you still carry, even if you renamed it?"],

  ["opinions", 4, "What's an opinion you hold that's milder than people expect?"],
  ["opinions", 5, "What's something you changed your mind about?"],
  ["opinions", 4, "Do you like a good debate or does it drain you?", "I like it", "It drains me"],
  ["opinions", 5, "What's a hill that's actually a hill for you?"],
  ["opinions", 4, "Hot takes at dinner: fun or please no?", "Fun", "Please no"],
  ["opinions", 6, "How do you want people to disagree with you?"],
  ["opinions", 5, "What's a popular opinion you don't share, without needing anyone to convert?"],
  ["opinions", 4, "Do you decide quickly or collect a lot of input?", "Decide quickly", "Collect input"],
  ["opinions", 5, "What's a topic you love talking about with someone who sees it differently?"],
  ["opinions", 6, "When was the last time someone actually updated your view?"],
  ["opinions", 4, "Would you rather be right or be kind, if you had to pick in a small moment?", "Right", "Kind"],
  ["opinions", 5, "What's an opinion you keep because you lived it, not because you read it?"],
  ["opinions", 4, "Group consensus or 'I'll go with the flow'?", "I want a say", "I can flow"],
  ["opinions", 5, "What's something you think is underrated?"],
  ["opinions", 6, "What does it take for you to trust someone's judgment?"],
  ["opinions", 4, "Strong opinions, loosely held — is that you?", "Yes", "No, I hold tight"],
  ["opinions", 5, "What's a 'best of' list you could write instantly?"],
  ["opinions", 4, "Do you like ranking things for fun?", "Yes", "No"],
  ["opinions", 5, "What's a taste of yours that you stopped explaining?"],

  ["embarrassing", 4, "What's a lightly embarrassing story you don't mind telling?"],
  ["embarrassing", 5, "What's something awkward you did that you can laugh about now?"],
  ["embarrassing", 4, "Do you cringe later or in the moment?", "Later", "In the moment"],
  ["embarrassing", 5, "What's a social stumble you survived and even reused as a joke?"],
  ["embarrassing", 4, "Would you rather trip in public or forget someone's name?", "Trip", "Forget a name"],
  ["embarrassing", 6, "What's an embarrassing moment that actually made you kinder?"],
  ["embarrassing", 5, "What's a fashion, hair, or username choice from the past?"],
  ["embarrassing", 4, "Do you replay conversations in the shower?", "Yes", "Not really"],
  ["embarrassing", 5, "What's a time you misunderstood a situation completely?"],
  ["embarrassing", 4, "Karaoke bravery or absolutely not?", "Karaoke", "Absolutely not"],
  ["embarrassing", 5, "What's the funniest way you've been obviously wrong?"],
  ["embarrassing", 6, "How do you recover when you feel awkward?"],
  ["embarrassing", 4, "Would you rather send a text to the wrong person or wave at a stranger?", "Wrong text", "Wrong wave"],
  ["embarrassing", 5, "What's a compliment you took as an insult at first?"],
  ["embarrassing", 4, "Do you tell on yourself, or hope nobody noticed?", "I tell on myself", "Hope nobody noticed"],
  ["embarrassing", 5, "What's a skill you attempted in public too soon?"],
  ["embarrassing", 6, "What's something you used to hide that you don't hide as much?"],
  ["embarrassing", 4, "Cringe comedy: love it or too close to home?", "Love it", "Too close"],
  ["embarrassing", 5, "What's a nickname origin story that's a little mortifying?"],

  ["habits", 4, "What's a habit that makes your day run smoother?"],
  ["habits", 5, "What's a habit you're trying to be more gentle about changing?"],
  ["habits", 4, "Same breakfast or variety?", "Same", "Variety"],
  ["habits", 5, "What's something you do on autopilot that you'd like to do on purpose?"],
  ["habits", 4, "Phone-first morning or delay the scroll?", "Phone first", "Delay it"],
  ["habits", 6, "What habit of yours is really a form of self-respect?"],
  ["habits", 5, "What's a tiny organizing system that you swear by?"],
  ["habits", 4, "Early errands or weekend pile-up?", "Early errands", "Weekend pile-up"],
  ["habits", 5, "What's a habit you copied from someone you admire?"],
  ["habits", 6, "What do you do when you notice you're avoiding something?"],
  ["habits", 4, "Lists everywhere or trust the brain?", "Lists", "Trust the brain"],
  ["habits", 5, "What's a wind-down habit that actually works?"],
  ["habits", 4, "Shoes by the door or shoes wherever they land?", "By the door", "Wherever"],
  ["habits", 5, "What's a weekly reset that helps you feel human again?"],
  ["habits", 6, "Which habit would you most like a friend to notice and cheer for?"],
  ["habits", 4, "Water bottle person: yes or I forget?", "Yes", "I forget"],
  ["habits", 5, "What's a 'I'll just check quickly' habit you have?"],
  ["habits", 4, "Make the bed or leave it?", "Make it", "Leave it"],
  ["habits", 5, "What's a hobby that became a habit without you planning it?"],

  ["emotions", 5, "What emotion is easiest for you to show?"],
  ["emotions", 6, "What emotion do you tend to keep more private?"],
  ["emotions", 4, "Do you cry at movies, speeches, or almost never in public?", "Easily", "Almost never"],
  ["emotions", 5, "What helps you come back to yourself after you get overwhelmed?"],
  ["emotions", 6, "How do you like people to respond when you're sad — space, company, or solutions?", "Space / company", "Solutions"],
  ["emotions", 5, "What makes you feel calm in someone else's presence?"],
  ["emotions", 4, "Music, movement, or talking it out?", "Music / movement", "Talking"],
  ["emotions", 6, "What's a feeling you used to judge that you understand better now?"],
  ["emotions", 5, "When you're happy, how does it show?"],
  ["emotions", 4, "Do you name your feelings out loud or keep them unnamed for a while?", "Name them", "Keep them unnamed"],
  ["emotions", 6, "What does support look like when you're anxious?"],
  ["emotions", 5, "What kind of humor helps you when things are heavy?"],
  ["emotions", 4, "Journal, voice memo, or a trusted person?", "Write / record", "A person"],
  ["emotions", 5, "What's a small thing that can shift your whole mood?"],
  ["emotions", 6, "How can someone tell you're not okay even if you say you are?"],
  ["emotions", 4, "Big feelings in the moment or delayed reaction?", "In the moment", "Delayed"],
  ["emotions", 5, "What makes you feel proud in a quiet way?"],
  ["emotions", 6, "What's something that always makes you feel tender?"],
  ["emotions", 5, "How do you celebrate when something goes right?"],

  ["experiences", 5, "What's a life experience that split your story into before and after?"],
  ["experiences", 4, "Would you rather collect experiences or build a nest?", "Experiences", "A nest"],
  ["experiences", 6, "What's something you did once that still teaches you?"],
  ["experiences", 5, "What's a trip, job, or season that stretched you?"],
  ["experiences", 4, "Comfort zone: expand on purpose or when life makes you?", "On purpose", "When life makes me"],
  ["experiences", 6, "What's a risk that was worth it?"],
  ["experiences", 5, "What's a first day you still remember — school, job, city?"],
  ["experiences", 4, "Do you like being the new person or does it take a minute?", "I like it", "It takes a minute"],
  ["experiences", 6, "What's an experience you want while you're still this version of you?"],
  ["experiences", 5, "What's something ordinary you didn't know you'd miss until it changed?"],
  ["experiences", 4, "One big leap or lots of small experiments?", "Big leap", "Small experiments"],
  ["experiences", 6, "Who were you with during a moment that still feels defining?"],
  ["experiences", 5, "What's a cultural, spiritual, or community experience that shaped you?"],
  ["experiences", 4, "Do you say yes first or no first?", "Yes first", "No first"],
  ["experiences", 5, "What's a skill you have only because life required it?"],
  ["experiences", 6, "What's a chapter you'd title if your last few years were a book?"],
  ["experiences", 5, "What's something you tried because someone you trusted invited you?"],
  ["experiences", 4, "Nostalgic about the past or hungry for the next thing?", "Nostalgic", "Hungry for next"],
  ["experiences", 5, "What's a place you lived, even briefly, that left a mark?"],
  ["experiences", 5, "What's a conversation you still think about years later?"],
  ["experiences", 6, "When did you surprise yourself by handling something well?"],
  ["experiences", 4, "Do you like revisiting old chapters, or keep your eyes forward?", "Revisit", "Eyes forward"],
];
