export const SURFACE = [
  ["hobbies", 2, "What's a hobby you could talk about for hours?"],
  ["hobbies", 2, "What's something you do to unwind after a long day?"],
  ["hobbies", 3, "What's a hobby you tried once and immediately loved?"],
  ["hobbies", 2, "What's a hobby you tried and quietly dropped?"],
  ["hobbies", 2, "Do you prefer hobbies you do alone or with other people?", "Alone", "With people"],
  ["hobbies", 3, "What's a hobby people might not expect you to have?"],
  ["hobbies", 3, "What's something you've made with your hands that you're proud of?"],
  ["hobbies", 2, "What's a hobby you'd pick up if time and money weren't a factor?"],
  ["hobbies", 2, "What's the most 'you' way to spend a free Saturday?"],
  ["hobbies", 2, "Do you like finishing projects or starting them more?", "Finishing", "Starting"],
  ["hobbies", 2, "What's a skill you taught yourself just for fun?"],
  ["hobbies", 3, "What's something you could happily do every week for the rest of your life?"],
  ["hobbies", 2, "What's a hobby that always puts you in a better mood?"],
  ["hobbies", 2, "Indoor hobby or outdoor hobby — which feels more like you?", "Indoor", "Outdoor"],
  ["hobbies", 3, "What's a collection you have, or secretly want to start?"],
  ["hobbies", 2, "What's the last thing you got genuinely excited to learn?"],
  ["hobbies", 2, "What's something you do that feels like play, not work?"],
  ["hobbies", 3, "What's a hobby you wish more people asked you about?"],

  ["music", 1, "What's a song that instantly improves your mood?"],
  ["music", 2, "What kind of music do you put on when you're getting ready?"],
  ["music", 2, "Live concert or headphones-on-the-couch?", "Live concert", "Headphones at home"],
  ["music", 2, "What's an album you could replay without getting tired of it?"],
  ["music", 3, "What was the first song or artist you ever really loved?"],
  ["music", 2, "Do you notice lyrics first or the beat first?", "Lyrics", "The beat"],
  ["music", 2, "What's your go-to karaoke song, even if you never karaoke?"],
  ["music", 1, "What's a genre people are surprised you like?"],
  ["music", 2, "Morning music or late-night music — which is more you?", "Morning", "Late night"],
  ["music", 2, "What's a song that reminds you of a specific season?"],
  ["music", 3, "If you could only keep one playlist, what would it be for?"],
  ["music", 2, "What's a concert you would drop everything to attend?"],
  ["music", 1, "What's your favorite kind of background music while working?"],
  ["music", 2, "What's a song you know every word to?"],
  ["music", 2, "What's something you like that isn't considered 'cool' musically?"],
  ["music", 3, "What music did the people who raised you play around the house?"],
  ["music", 1, "Headphones or speakers?", "Headphones", "Speakers"],
  ["music", 2, "What's a movie or show soundtrack you actually listen to on its own?"],

  ["movies", 1, "What's a movie you can rewatch anytime?"],
  ["movies", 2, "What's the last show you got genuinely hooked on?"],
  ["movies", 2, "Comfort movie or brand-new release?", "Comfort movie", "Something new"],
  ["movies", 2, "What's a character you felt oddly understood by?"],
  ["movies", 1, "What's your favorite movie snack?"],
  ["movies", 3, "What's a film that surprised you by making you cry?"],
  ["movies", 2, "Do you like watching with commentary, or in silence?", "Talking through it", "Silence, please"],
  ["movies", 2, "What's a TV show you wish more people had seen?"],
  ["movies", 1, "Animated or live-action, if you had to pick tonight?", "Animated", "Live-action"],
  ["movies", 2, "What's a movie you loved as a kid that still holds up?"],
  ["movies", 2, "Binge a whole season or one episode at a time?", "Binge", "One at a time"],
  ["movies", 3, "What's a story you keep recommending even if no one asked?"],
  ["movies", 2, "What's your favorite kind of ending: neat or messy?", "Neat", "Messy"],
  ["movies", 1, "Subtitled or dubbed?", "Subtitles", "Dubbed"],
  ["movies", 2, "What's a guilty-pleasure show you will not apologize for?"],
  ["movies", 2, "Theater or couch?", "Theater", "Couch"],
  ["movies", 3, "What's a movie quote you use in real life?"],
  ["movies", 2, "If your life had a genre, what would it be?"],

  ["food", 1, "What's your favorite comfort food?"],
  ["food", 2, "What's a meal you could eat once a week forever?"],
  ["food", 1, "Sweet or savory, most days?", "Sweet", "Savory"],
  ["food", 2, "What's a food you loved as a kid and still love?"],
  ["food", 2, "What's a food everyone likes that you just... don't?"],
  ["food", 3, "What's a meal that feels like home to you?"],
  ["food", 1, "Coffee, tea, or neither?", "Coffee", "Tea"],
  ["food", 2, "What's your go-to order when you can't decide?"],
  ["food", 2, "Cooking for fun or cooking for fuel?", "For fun", "For fuel"],
  ["food", 2, "What's a snack you pretend is a rare treat but is not?"],
  ["food", 1, "Breakfast for dinner: yes or no?", "Yes", "No"],
  ["food", 3, "What's a dish you'd want to learn from someone who makes it well?"],
  ["food", 2, "Spicy food: bring it on or keep it mild?", "Bring it on", "Keep it mild"],
  ["food", 2, "What's a restaurant you'd take someone to if you wanted them to like you?"],
  ["food", 1, "Pizza topping you will always defend?"],
  ["food", 2, "What's something you could teach someone to cook in 20 minutes?"],
  ["food", 2, "Sit-down meal or picnic-style eating?", "Sit-down", "Picnic-style"],
  ["food", 3, "What's a food memory that still makes you smile?"],

  ["travel", 2, "Where would you love to travel next?"],
  ["travel", 2, "Beach trip or city trip?", "Beach", "City"],
  ["travel", 3, "What's a place that felt more like you than you expected?"],
  ["travel", 2, "Do you overpack or underpack?", "Overpack", "Underpack"],
  ["travel", 1, "Window seat or aisle?", "Window", "Aisle"],
  ["travel", 2, "What's a trip you still talk about?"],
  ["travel", 3, "Would you rather travel slow for a month or pack a week with highlights?", "Slow month", "Packed week"],
  ["travel", 2, "What's your favorite thing to do in a new city on day one?"],
  ["travel", 2, "Adventure itinerary or wander with no plan?", "Itinerary", "Wander"],
  ["travel", 1, "Mountains or ocean?", "Mountains", "Ocean"],
  ["travel", 3, "What's a place from your childhood you'd like to visit again?"],
  ["travel", 2, "What's a souvenir you actually keep?"],
  ["travel", 2, "Road trip playlist: yours or whoever's driving?", "Mine", "The driver's"],
  ["travel", 1, "Early flight or red-eye?", "Early flight", "Red-eye"],
  ["travel", 3, "If money weren't a factor, where would you live for a year?"],
  ["travel", 2, "What's the best food you've ever eaten while traveling?"],
  ["travel", 2, "Museum day or outdoor day?", "Museum", "Outdoors"],
  ["travel", 2, "What's a tiny travel luxury you refuse to skip?"],

  ["interests", 2, "What's something you're casually obsessed with right now?"],
  ["interests", 3, "What's a topic you can nerd out about with almost no prompting?"],
  ["interests", 2, "Do you fall into Wikipedia holes, or do you bounce off them?", "I fall in", "I bounce off"],
  ["interests", 2, "What's a book, podcast, or essay that stuck with you?"],
  ["interests", 1, "What's a random fact you love telling people?"],
  ["interests", 2, "Are you more into making things or finding things?", "Making", "Finding"],
  ["interests", 3, "What's an interest you outgrew, and do you miss it?"],
  ["interests", 2, "What's something you want to learn just because it's cool?"],
  ["interests", 2, "Museums, thrift stores, or record shops — pick a happy place."],
  ["interests", 1, "Do you like puzzles, trivia, or neither?", "Puzzles", "Trivia"],
  ["interests", 2, "What's a documentary topic you'd actually watch?"],
  ["interests", 3, "What's a question you've been turning over lately for fun?"],
  ["interests", 2, "Are you a collector or a minimalist with your stuff?", "Collector", "Minimalist"],
  ["interests", 2, "What's a skill that's useless and delightful?"],
  ["interests", 1, "Physical books or e-books?", "Physical", "E-books"],
  ["interests", 2, "What's a style of art, fashion, or design you're drawn to?"],
  ["interests", 2, "What's something you researched way too deeply for no reason?"],
  ["interests", 3, "If you had a tiny museum of your life, what would be in it?"],

  ["sports", 1, "Do you like watching sports, playing them, both, or neither?"],
  ["sports", 2, "What's a sport you enjoy even if you're not great at it?"],
  ["sports", 2, "Team sports or solo sports?", "Team", "Solo"],
  ["sports", 1, "What's your casual 'I'll play if asked' sport?"],
  ["sports", 3, "Was there a sport that mattered a lot to you growing up?"],
  ["sports", 2, "What's more fun: playing, watching, or the snacks?", "Playing", "Watching"],
  ["sports", 2, "What's a sports moment you still remember?"],
  ["sports", 1, "Early-morning workout or evening workout?", "Morning", "Evening"],
  ["sports", 2, "Competitive or just-for-fun when you play?", "Competitive", "Just for fun"],
  ["sports", 2, "What's an active thing you'd like to try once?"],
  ["sports", 1, "Walk, run, or bike?", "Walk", "Bike"],
  ["sports", 3, "Did you ever surprise yourself by being decent at something physical?"],
  ["sports", 2, "What's your favorite way to be outdoors?"],
  ["sports", 2, "Olympics: summer or winter?", "Summer", "Winter"],
  ["sports", 1, "What's a game-day snack you take seriously?"],
  ["sports", 2, "Do you keep score in casual games?", "Yes", "No"],
  ["sports", 2, "What's a sport you don't understand but respect?"],
  ["sports", 3, "If you had to join a rec league tomorrow, which one?"],

  ["animals", 1, "Cats or dogs?", "Cats", "Dogs"],
  ["animals", 2, "What's an animal you feel strangely connected to?"],
  ["animals", 1, "Would you rather have a pet that cuddles or one that's independent?", "Cuddles", "Independent"],
  ["animals", 2, "What's the best pet name you've ever heard?"],
  ["animals", 3, "Did you have a childhood pet that still lives in your head?"],
  ["animals", 2, "Zoo, aquarium, or farm day?", "Zoo", "Aquarium"],
  ["animals", 1, "What's your spirit animal in the least serious sense?"],
  ["animals", 2, "Are you the person who stops to photograph every dog?", "Yes", "No"],
  ["animals", 2, "What's an animal you'd love to see in the wild?"],
  ["animals", 1, "Indoor cat life or big backyard energy?", "Indoor cozy", "Big backyard"],
  ["animals", 3, "What kind of caretaking comes naturally to you?"],
  ["animals", 2, "Birds, fish, or reptiles — unexpected pet of choice?"],
  ["animals", 2, "What's a cute animal video genre you always watch?"],
  ["animals", 1, "Wake up with a pet in your face: dream or nightmare?", "Dream", "Nightmare"],
  ["animals", 2, "If you could talk to one species for a day, which?"],
  ["animals", 2, "What's an animal people are scared of that you like?"],
  ["animals", 3, "What would your pet say about your personality?"],
  ["animals", 1, "House full of plants and pets, or keep it simple?", "Full house", "Keep it simple"],

  ["games", 1, "What's your favorite game right now?"],
  ["games", 2, "Board games, video games, or party games?", "Board games", "Video games"],
  ["games", 2, "Do you play to win or play to hang out?", "To win", "To hang out"],
  ["games", 3, "What's a game that meant a lot to you at a certain age?"],
  ["games", 1, "Co-op or versus?", "Co-op", "Versus"],
  ["games", 2, "What's a game you're surprisingly good at?"],
  ["games", 2, "What's a game you love that you have to explain too much?"],
  ["games", 1, "Easy fun or steep learning curve?", "Easy fun", "Steep curve"],
  ["games", 2, "What's your house-rule philosophy: official or chaos?", "Official rules", "House chaos"],
  ["games", 3, "Who do you most like playing games with?"],
  ["games", 2, "Puzzle games or story games?", "Puzzles", "Story"],
  ["games", 1, "What's a mobile game you will not admit the hours on?"],
  ["games", 2, "Dice, cards, or digital?", "Cards", "Digital"],
  ["games", 2, "What's a game night snack that is non-negotiable?"],
  ["games", 3, "What's a game that taught you something about yourself?"],
  ["games", 1, "Single-player evening or multiplayer chaos?", "Single-player", "Multiplayer"],
  ["games", 2, "What's a childhood game you can still play by heart?"],
  ["games", 2, "If GTKY had a boss level, what would it be?"],

  ["school", 2, "What subject did you secretly (or not secretly) like?"],
  ["school", 2, "Group project: leader, helper, or last-minute hero?", "Leader", "Helper"],
  ["school", 3, "Who was a teacher that actually got through to you?"],
  ["school", 1, "Did you prefer tests or projects?", "Tests", "Projects"],
  ["school", 2, "What was your school lunch personality?"],
  ["school", 2, "Were you early to class or sliding in on time?", "Early", "Right on time"],
  ["school", 3, "What's something school made you think you weren't good at?"],
  ["school", 2, "What club, team, or hallway role felt like yours?"],
  ["school", 1, "Handwriting or typing — which feels more like thinking?", "Handwriting", "Typing"],
  ["school", 2, "What's a school smell, sound, or season you remember clearly?"],
  ["school", 2, "Did you decorate your notebooks or keep them plain?", "Decorate", "Plain"],
  ["school", 3, "What's a lesson you learned outside the lesson plan?"],
  ["school", 1, "Library kid or gym kid?", "Library", "Gym"],
  ["school", 2, "What's a class you wish you'd taken?"],
  ["school", 2, "Were you the highlighter type or the 'I'll remember it' type?", "Highlighter", "I'll remember"],
  ["school", 3, "What did 'doing well' mean to you back then?"],
  ["school", 2, "What's a school friendship dynamic you still think about?"],
  ["school", 1, "Field trip energy: excited or socially tired?", "Excited", "Socially tired"],

  ["work", 2, "What's a small part of your workday you actually like?"],
  ["work", 2, "Headphones on or door-open collaborator?", "Headphones on", "Door open"],
  ["work", 3, "What kind of work makes time disappear for you?"],
  ["work", 1, "Morning meetings or afternoon deep work?", "Mornings", "Afternoons"],
  ["work", 2, "What's a job you romanticized as a kid?"],
  ["work", 2, "Do you like having a routine, or do you like variety at work?", "Routine", "Variety"],
  ["work", 3, "What's something you're better at now than you were two years ago?"],
  ["work", 1, "Office snacks: sweet, salty, or both?", "Sweet", "Salty"],
  ["work", 2, "What's a work skill you picked up the hard way?"],
  ["work", 2, "Camera on or camera off, if you get a choice?", "Camera on", "Camera off"],
  ["work", 3, "What does a good boss feel like to you?"],
  ["work", 2, "What's your ideal 'I got a lot done' feeling?"],
  ["work", 1, "To-do list or memory?", "To-do list", "Memory"],
  ["work", 2, "What's a totally different job you'd try for a month?"],
  ["work", 2, "Do you like mentoring, being mentored, or both?", "Mentoring", "Being mentored"],
  ["work", 3, "When do you feel most competent?"],
  ["work", 1, "Friday energy or Monday reset — which is more you?", "Friday", "Monday"],
  ["work", 2, "What's a tiny workplace luxury that matters more than it should?"],

  ["places", 2, "What's a place in your town that feels like yours?"],
  ["places", 1, "Coffee shop, park, or bookstore?", "Coffee shop", "Bookstore"],
  ["places", 3, "Where do you go when you need to think?"],
  ["places", 2, "What's a view you never get tired of?"],
  ["places", 2, "Crowded city night or quiet neighborhood evening?", "City night", "Quiet evening"],
  ["places", 1, "Window table or corner booth?", "Window", "Corner booth"],
  ["places", 3, "What's a place that always makes you feel smaller in a good way?"],
  ["places", 2, "What's your favorite kind of weather to be outside in?"],
  ["places", 2, "Homebody hangout or 'let's go somewhere'?", "Homebody", "Let's go out"],
  ["places", 1, "Sunrise or sunset?", "Sunrise", "Sunset"],
  ["places", 2, "What's a building, street, or trail you'd give a tour of?"],
  ["places", 3, "Where were you the last time you thought, 'I like my life right now'?"],
  ["places", 2, "What's your ideal background noise: people, nature, or quiet?", "People", "Quiet"],
  ["places", 1, "Porch, balcony, or none of the above?", "Porch / balcony", "Neither"],
  ["places", 2, "What's a place you keep meaning to go back to?"],
  ["places", 2, "Farmer's market energy or midnight diner energy?", "Farmer's market", "Midnight diner"],
  ["places", 3, "If someone visited you for 24 hours, where would you take them first?"],
  ["places", 1, "Lights low or bright room?", "Lights low", "Bright room"],

  ["lifestyle", 1, "Morning person or night owl?", "Morning person", "Night owl"],
  ["lifestyle", 2, "What's your ideal slow morning look like?"],
  ["lifestyle", 2, "Plan the weekend or see what happens?", "Plan it", "See what happens"],
  ["lifestyle", 1, "Phone on the table or phone in another room?", "On the table", "Another room"],
  ["lifestyle", 3, "What does a restful day actually require for you?"],
  ["lifestyle", 2, "What's a small daily ritual you protect?"],
  ["lifestyle", 1, "Big breakfast or skip-to-lunch?", "Big breakfast", "Skip to lunch"],
  ["lifestyle", 2, "What's your comfort clothing philosophy?"],
  ["lifestyle", 2, "Clean as you go or chaos-then-reset?", "Clean as you go", "Chaos then reset"],
  ["lifestyle", 3, "What time of day do you feel most like yourself?"],
  ["lifestyle", 1, "Showers: morning or night?", "Morning", "Night"],
  ["lifestyle", 2, "What's something you do to make a regular day feel nicer?"],
  ["lifestyle", 2, "Guest-ready home or lived-in home?", "Guest-ready", "Lived-in"],
  ["lifestyle", 1, "Candles / cozy lighting: yes or extra?", "Yes", "Extra"],
  ["lifestyle", 3, "What's a habit you're quietly proud of?"],
  ["lifestyle", 2, "What's your relationship with alarms and snooze buttons?"],
  ["lifestyle", 2, "Cooking night or takeout night when you're tired?", "Cooking", "Takeout"],
  ["lifestyle", 1, "One long walk or a short workout?", "Long walk", "Short workout"],

  ["fun", 1, "Would you rather be able to read minds or see the future?", "Read minds", "See the future"],
  ["fun", 1, "Pancakes or waffles?", "Pancakes", "Waffles"],
  ["fun", 2, "What's a tiny hill you will die on?"],
  ["fun", 1, "Hot weather or cold weather?", "Hot", "Cold"],
  ["fun", 2, "What's the funniest thing that's happened to you recently?"],
  ["fun", 1, "Text essay or voice note?", "Text", "Voice note"],
  ["fun", 2, "What's a nickname you've had, wanted, or refused?"],
  ["fun", 1, "Would you rather always be slightly early or slightly late?", "Early", "Late"],
  ["fun", 2, "What's your signature dance-at-a-wedding energy?"],
  ["fun", 1, "Sweet popcorn or salty popcorn?", "Sweet", "Salty"],
  ["fun", 3, "What's a story you love telling even if it makes you look silly?"],
  ["fun", 1, "Invisible or flight?", "Invisible", "Flight"],
  ["fun", 2, "What's a weirdly specific thing that delights you?"],
  ["fun", 1, "Board game night or movie night?", "Board games", "Movie night"],
  ["fun", 2, "What's your go-to impression, joke, or bit?"],
  ["fun", 1, "Would you rather have a rewind button or a pause button for life?", "Rewind", "Pause"],
];
